version: "3.9"

services:
  postgres:
    image: postgres:15-bullseye
    container_name: taxi-postgres
    environment:
      POSTGRES_USER: taxi
      POSTGRES_PASSWORD: taxi
      POSTGRES_DB: taxi_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "taxi"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

volumes:
  postgres-data:
